# Site settings
author: David Masterson
title: My programming progress
header-img: img/home-bg.png
email: david73180@gmail.com
copyright_name: David Masterson
description: > # this means to ignore newlines until "baseurl:"
  progress report
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Shadow073180

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
